/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Cheap check that the process is up. Never touches dependencies.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks Postgres, Redis and S3. Returns 503 if any dependency is down.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadyResponse"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluated feature flags (development only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlagsResponse"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemInput: {
            /** @description URI reference identifying the problem type */
            type: string;
            title: string;
            status: number;
            /** @description Stable machine-readable error code, e.g. VALIDATION_FAILED */
            code: string;
            detail?: string;
            instance?: string;
            requestId?: string;
            /** @description Field-level validation errors */
            errors?: {
                path: string;
                message: string;
            }[];
        };
        HealthResponseInput: {
            /** @constant */
            status: "ok";
            uptimeSeconds: number;
        };
        DependencyCheckInput: {
            /** @enum {string} */
            status: "up" | "down";
            latencyMs: number;
            error?: string;
        };
        ReadyResponseInput: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            checks: {
                postgres: components["schemas"]["DependencyCheckInput"];
                redis: components["schemas"]["DependencyCheckInput"];
                s3: components["schemas"]["DependencyCheckInput"];
            };
        };
        EvaluatedFlagInput: {
            key: string;
            enabled: boolean;
            /** @enum {string} */
            source: "override" | "database" | "default";
        };
        FlagsResponseInput: {
            flags: components["schemas"]["EvaluatedFlagInput"][];
        };
        Problem: {
            /** @description URI reference identifying the problem type */
            type: string;
            title: string;
            status: number;
            /** @description Stable machine-readable error code, e.g. VALIDATION_FAILED */
            code: string;
            detail?: string;
            instance?: string;
            requestId?: string;
            /** @description Field-level validation errors */
            errors?: {
                path: string;
                message: string;
            }[];
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            uptimeSeconds: number;
        };
        DependencyCheck: {
            /** @enum {string} */
            status: "up" | "down";
            latencyMs: number;
            error?: string;
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            checks: {
                postgres: components["schemas"]["DependencyCheck"];
                redis: components["schemas"]["DependencyCheck"];
                s3: components["schemas"]["DependencyCheck"];
            };
        };
        EvaluatedFlag: {
            key: string;
            enabled: boolean;
            /** @enum {string} */
            source: "override" | "database" | "default";
        };
        FlagsResponse: {
            flags: components["schemas"]["EvaluatedFlag"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
