import { sql } from 'drizzle-orm';
import { boolean, index, jsonb, pgTable, text, timestamp, unique, uuid } from 'drizzle-orm/pg-core';

/** UUIDv7 primary key generated by Postgres 18's native `uuidv7()`. */
const id = () => uuid('id').primaryKey().default(sql`uuidv7()`);
const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

/**
 * Feature flags. `workspace_id = NULL` is the global default; a row with a
 * workspace id overrides it for that workspace.
 */
export const featureFlags = pgTable(
  'feature_flags',
  {
    id: id(),
    key: text('key').notNull(),
    workspaceId: uuid('workspace_id'),
    enabled: boolean('enabled').notNull().default(false),
    rules: jsonb('rules').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    updatedAt: timestamptz('updated_at')
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  // NULLS NOT DISTINCT so there can only be one global (workspace_id IS NULL) row per key.
  (t) => [unique('feature_flags_key_workspace_id_key').on(t.key, t.workspaceId).nullsNotDistinct()],
);

/** Transactional outbox: written in the same transaction as the state change it describes. */
export const domainEvents = pgTable(
  'domain_events',
  {
    id: id(),
    type: text('type').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull(),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    processedAt: timestamptz('processed_at'),
  },
  (t) => [
    index('domain_events_unprocessed_idx')
      .on(t.createdAt)
      .where(sql`${t.processedAt} IS NULL`),
  ],
);

export type FeatureFlagRow = typeof featureFlags.$inferSelect;
export type DomainEventRow = typeof domainEvents.$inferSelect;
export type NewDomainEvent = typeof domainEvents.$inferInsert;
